### get goals
GET https://jwt-auth-eight-neon.vercel.app/goals
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjI3NSwibmFtZSI6Ik1BSERBTEVOQSIsImVtYWlsIjoiMTExMjAyMzE1MjEzQG1ocy5kaW51cy5hYy5pZCIsImlhdCI6MTc4MDk2NzU2MSwiZXhwIjoxNzgxMDUzOTYxfQ.HTke76EefdgXDIy1nPnGnzLZuC65QF98PddlOoYnJZs

### post goals
POST https://jwt-auth-eight-neon.vercel.app/goals
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjI3NSwibmFtZSI6Ik1BSERBTEVOQSIsImVtYWlsIjoiMTExMjAyMzE1MjEzQG1ocy5kaW51cy5hYy5pZCIsImlhdCI6MTc4MDk2NzU2MSwiZXhwIjoxNzgxMDUzOTYxfQ.HTke76EefdgXDIy1nPnGnzLZuC65QF98PddlOoYnJZs
Content-Type: application/json

{
  "target_amount": 5000,
  "present_amount": 2100
}